import os
from typing import TypedDict, Annotated, Sequence
import operator
from langchain_core.messages import BaseMessage, HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode, tools_condition
from langchain_core.tools import tool

# Load environment variables (Make sure to create a .env file with OPENAI_API_KEY)
from dotenv import load_dotenv
load_dotenv()

# 1. Define a tool
@tool
def get_weather(location: str) -> str:
    """Get the weather for a specific location."""
    # This is a mock tool. In reality, you'd call an API here.
    return f"The weather in {location} is sunny and 75°F."

tools = [get_weather]

# 2. Define State
class AgentState(TypedDict):
    # The `operator.add` reducer is critical here to accumulate the chat history
    messages: Annotated[Sequence[BaseMessage], operator.add]

# 3. Define the LLM Node
def call_model(state: AgentState):
    print("--- Calling LLM ---")
    # Initialize the LLM and bind the tools to it
    try:
        # Requires OPENAI_API_KEY in environment
        llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
        llm_with_tools = llm.bind_tools(tools)
        
        # Invoke the LLM with the current list of messages
        response = llm_with_tools.invoke(state["messages"])
        
        # We return a list, because of operator.add, it will be appended to the state
        return {"messages": [response]}
    except Exception as e:
        print(f"\n[ERROR] Failed to call LLM. Did you set OPENAI_API_KEY in a .env file? Error: {e}")
        return {"messages": []}

# 4. Build the Graph
builder = StateGraph(AgentState)

# Add nodes
builder.add_node("agent", call_model)
# ToolNode is a prebuilt LangGraph node that executes the tools requested by the LLM
builder.add_node("tools", ToolNode(tools))

# Add edges
builder.add_edge(START, "agent")

# tools_condition checks if the LLM returned tool calls. 
# If yes, it routes to "tools". If no, it routes to END.
builder.add_conditional_edges(
    "agent",
    tools_condition, 
)

# After tools run, always return to the agent so it can read the tool output and respond
builder.add_edge("tools", "agent")

graph = builder.compile()

if __name__ == "__main__":
    print("Starting Tool Agent Graph...")
    
    # Verify API key exists before running
    if not os.environ.get("OPENAI_API_KEY"):
        print("\n[WARNING] OPENAI_API_KEY not found in environment or .env file.")
        print("The LLM call will fail. Please create a .env file and add your key.\n")
    
    # User asks a question that requires the tool
    user_input = "What is the weather in San Francisco?"
    print(f"User: {user_input}\n")
    
    initial_state = {"messages": [HumanMessage(content=user_input)]}
    
    # Run the graph using .stream() to see the process step-by-step
    for event in graph.stream(initial_state):
        for key, value in event.items():
            print(f"Node '{key}' finished executing.")
            if "messages" in value and value["messages"]:
                # Print the latest message generated by the node
                latest_msg = value["messages"][-1]
                print(f"Output: {latest_msg.content or '(Tool Call Executed)'}\n")
